name = "vistai-worker"
main = "worker/worker.js"
compatibility_date = "2025-05-26"
compatibility_flags = ["nodejs_compat"]

[vars]
# OPENROUTER_API_KEY should be set in the Cloudflare dashboard or via wrangler
# API_BASE_URL should be set in Cloudflare dashboard or via wrangler
# ACCESS_CONTROL_ALLOW_ORIGIN controls allowed CORS origins
# https://developers.cloudflare.com/secrets-store/integrations/workers/
secrets_store_secrets = [
  { binding = "OPENROUTER_API_KEY", store_id= "3ae45c355bc742238784351f929bc706", secret_name = "OPENROUTER_API_KEY" }
]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "vistai"
# Replace with your D1 database ID
database_id = "88697d9a-39f5-4698-9df0-5b8ff40ffb7a"
