name = "vistai-worker"
main = "worker/worker.js"
compatibility_date = "2025-05-26"
compatibility_flags = ["nodejs_compat"]

[vars]
# Environment variables can be set in Cloudflare dashboard or via wrangler secret put
# ACCESS_CONTROL_ALLOW_ORIGIN = "*"  # For development, restrict in production
# JWT_SECRET = "your-secure-jwt-secret-here"  # Set via wrangler secret put JWT_SECRET

[observability]
enabled = true

# Production configuration
[env.production]
name = "vistai-worker-prod"
vars = { ACCESS_CONTROL_ALLOW_ORIGIN = "https://vistai.pages.dev" }

# Optional: Development environment
[env.development]  
name = "vistai-worker-dev"
vars = { ACCESS_CONTROL_ALLOW_ORIGIN = "*" }

[[d1_databases]]
binding = "DB"
database_name = "vistai"
# IMPORTANT: Replace with your actual D1 database ID from Cloudflare dashboard
# Run: wrangler d1 create vistai
# Then copy the database_id from the output
database_id = "88697d9a-39f5-4698-9df0-5b8ff40ffb7a"

# Production database (optional - use same DB or create separate one)
[[env.production.d1_databases]]
binding = "DB"
database_name = "vistai-prod"
database_id = "88697d9a-39f5-4698-9df0-5b8ff40ffb7a"
