name = "vistai-worker"
main = "worker/worker.js"
compatibility_date = "2024-06-05"

[vars]
# OPENROUTER_API_KEY should be set in the Cloudflare dashboard or via wrangler

[observability]
enabled = true
