name = "vistai-worker"
main = "worker/worker.js"
compatibility_date = "2025-05-26"

[vars]
# OPENROUTER_API_KEY should be set in the Cloudflare dashboard or via wrangler
# API_BASE_URL should be set in Cloudflare dashboard or via wranlger

[observability]
enabled = true
