name: Deploy Cloudflare Worker

permissions:
  contents: read

on:
  push:
    branches: [ main ]
    paths:
      - 'worker/**'
      - 'wrangler.toml'
      - '.github/workflows/deploy-worker.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: vistAI
    steps:
      - uses: actions/checkout@v3
      - name: Publish worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: deploy
